### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by fuxiocteract** [kadirahq/lokka#26]
when importing lokka-transport-http, getting these errors:

WARNING in ./~/encoding/lib/iconv-loader.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./~/encoding/lib/iconv-loader.js 9:12-34

ERROR in ./~/iconv-lite/encodings/tables/gb18030-ranges.json
Module parse failed: C:\Users\黄硕\Project\toodu\node_modules\iconv-lite\encodings\tables\gb18030-ranges.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:9)
    at Parser.pp$4.raise (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseBlock (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:981:25)
    at Parser.pp$1.parseStatement (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\黄硕\Project\toodu\node_modules\acorn\dist\acorn.js:3098:39)
 @ ./~/iconv-lite/encodings/dbcs-data.js 99:37-76

**Comment by fuxiocteract** [comment]
Add a json-loader to webpack and it seems to have solved it for now.

**Comment by ljubic** [comment]
`npm install --save-dev json-loader`

```
module: {
    loaders: [
      { test: /\.json$/, loader: "json-loader" }
    ]
}
```

**Comment by machineghost** [comment]
It would be nice if the instruction line on the front page:

     npm i --save lokka lokka-transport-http

could be changed to reflect this:

    npm i --save lokka lokka-transport-http

    #  For Webpack users only
    npm i --save-dev json-loader

    # NOTE: You will also need to add a module.loaders entry for the loader to webpack.config:
    module: {
        loaders: [
            {loader: 'json', test: /\.json$/},
        ]
    }

**Comment by arunoda** [comment]
@machineghost could you send me a PR for that.

**Comment by lanwin** [comment]
The problem is this dosnt help when using create-react-app.
